### ISSUE TITLE
README.md 演示链接总是超时哦

### ISSUE THREAD

**Issue by margin-0** [cliclitv/clicli-admin#2]
![image](https://user-images.githubusercontent.com/23308724/49361043-e13c4f00-f715-11e8-9d17-ce03d9438ef2.png)
![image](https://user-images.githubusercontent.com/23308724/49361081-016c0e00-f716-11e8-91eb-d6293c819f1d.png)
因为一个功能 来看源码的，发现这个小问题了。

**Comment by 132yse** [comment]
admin.clicli.top
